version: 2

base: &base
  working_directory: ~/Koa-Starter
  docker:
    - image: circleci/node:14

jobs:
  test:
    <<: *base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Build the application
          command: docker-compose exec default yarn build

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
