version: 2.1

executors:
  koa-starter:
    docker:
      - image: circleci/node:14

jobs:
  test:
    executor: koa-starter
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Build the application
          command: docker-compose exec default yarn build

workflows:
  version: 2

  parallel-test:
    jobs:
      - test
